// Dictionnaire des codes IATA compagnies aériennes → nom complet.
// Utilisé pour transformer "ET" saisi par l'agent en "Ethiopian Airlines" côté client.

export const IATA_AIRLINES: Record<string, string> = {
  // Europe
  AF: "Air France",
  KL: "KLM",
  BA: "British Airways",
  LH: "Lufthansa",
  LX: "Swiss",
  OS: "Austrian Airlines",
  SN: "Brussels Airlines",
  IB: "Iberia",
  TP: "TAP Air Portugal",
  AZ: "ITA Airways",
  AY: "Finnair",
  SK: "SAS",
  DY: "Norwegian",
  FR: "Ryanair",
  U2: "easyJet",
  VY: "Vueling",
  HV: "Transavia",
  TO: "Transavia France",
  EW: "Eurowings",
  EI: "Aer Lingus",
  LO: "LOT Polish Airlines",
  OK: "Czech Airlines",
  RO: "Tarom",
  A3: "Aegean Airlines",
  TK: "Turkish Airlines",
  PC: "Pegasus Airlines",
  // Moyen-Orient & Asie
  EK: "Emirates",
  EY: "Etihad Airways",
  QR: "Qatar Airways",
  SV: "Saudia",
  GF: "Gulf Air",
  WY: "Oman Air",
  KU: "Kuwait Airways",
  ME: "Middle East Airlines",
  RJ: "Royal Jordanian",
  LY: "El Al",
  SQ: "Singapore Airlines",
  CX: "Cathay Pacific",
  TG: "Thai Airways",
  MH: "Malaysia Airlines",
  GA: "Garuda Indonesia",
  PR: "Philippine Airlines",
  VN: "Vietnam Airlines",
  CI: "China Airlines",
  BR: "EVA Air",
  KE: "Korean Air",
  OZ: "Asiana Airlines",
  JL: "Japan Airlines",
  NH: "ANA All Nippon Airways",
  CA: "Air China",
  MU: "China Eastern",
  CZ: "China Southern",
  AI: "Air India",
  UK: "Vistara",
  "6E": "IndiGo",
  UL: "SriLankan Airlines",
  // Amériques
  AA: "American Airlines",
  DL: "Delta Air Lines",
  UA: "United Airlines",
  B6: "JetBlue",
  WN: "Southwest Airlines",
  AS: "Alaska Airlines",
  AC: "Air Canada",
  WS: "WestJet",
  AM: "Aeromexico",
  CM: "Copa Airlines",
  AV: "Avianca",
  LA: "LATAM Airlines",
  AR: "Aerolíneas Argentinas",
  G3: "Gol",
  // Afrique
  ET: "Ethiopian Airlines",
  KQ: "Kenya Airways",
  SA: "South African Airways",
  AT: "Royal Air Maroc",
  TU: "Tunisair",
  AH: "Air Algérie",
  MS: "EgyptAir",
  MK: "Air Mauritius",
  // Océan Indien & Pacifique
  QF: "Qantas",
  NZ: "Air New Zealand",
  VA: "Virgin Australia",
  UU: "Air Austral",
  TX: "Air Caraïbes",
  BJ: "Nouvelair",
  SS: "Corsair",
  XK: "Air Corsica",
};

/** Renvoie le nom complet de la compagnie, ou la valeur saisie si inconnue (ex : "Air France" tapé en clair). */
export function airlineName(code: string | null | undefined): string {
  if (!code) return "";
  const c = code.trim().toUpperCase();
  return IATA_AIRLINES[c] ?? code.trim();
}
