// Dictionnaire des principaux codes IATA → nom lisible (Ville + aéroport).
// Couvre les hubs européens, américains, asiatiques, africains et long-courriers fréquents.
// L'agent saisit en codes IATA, le client voit un nom clair.

export const IATA_AIRPORTS: Record<string, string> = {
  // France
  CDG: "Paris Charles-de-Gaulle",
  ORY: "Paris Orly",
  LBG: "Paris Le Bourget",
  BVA: "Paris Beauvais",
  MRS: "Marseille Provence",
  NCE: "Nice Côte d'Azur",
  LYS: "Lyon Saint-Exupéry",
  TLS: "Toulouse Blagnac",
  BOD: "Bordeaux Mérignac",
  NTE: "Nantes Atlantique",
  MPL: "Montpellier Méditerranée",
  SXB: "Strasbourg Entzheim",
  BIQ: "Biarritz Pays Basque",
  AJA: "Ajaccio Napoléon Bonaparte",
  BIA: "Bastia Poretta",
  FSC: "Figari Sud Corse",
  CLY: "Calvi Sainte-Catherine",
  RNS: "Rennes Saint-Jacques",
  BES: "Brest Bretagne",
  LIL: "Lille Lesquin",
  // Europe
  LHR: "Londres Heathrow",
  LGW: "Londres Gatwick",
  STN: "Londres Stansted",
  LCY: "Londres City",
  LTN: "Londres Luton",
  AMS: "Amsterdam Schiphol",
  BRU: "Bruxelles Zaventem",
  CRL: "Bruxelles Charleroi",
  FRA: "Francfort",
  MUC: "Munich",
  TXL: "Berlin Tegel",
  BER: "Berlin Brandenburg",
  HAM: "Hambourg",
  DUS: "Düsseldorf",
  CGN: "Cologne Bonn",
  ZRH: "Zurich",
  GVA: "Genève",
  BSL: "Bâle Mulhouse",
  VIE: "Vienne",
  MAD: "Madrid Barajas",
  BCN: "Barcelone El Prat",
  AGP: "Malaga",
  PMI: "Palma de Majorque",
  IBZ: "Ibiza",
  LIS: "Lisbonne",
  OPO: "Porto",
  FNC: "Madère Funchal",
  FCO: "Rome Fiumicino",
  CIA: "Rome Ciampino",
  MXP: "Milan Malpensa",
  LIN: "Milan Linate",
  BGY: "Milan Bergame",
  VCE: "Venise Marco Polo",
  NAP: "Naples",
  CTA: "Catane",
  PMO: "Palerme",
  ATH: "Athènes",
  JTR: "Santorin",
  JMK: "Mykonos",
  HER: "Héraklion (Crète)",
  IST: "Istanbul",
  SAW: "Istanbul Sabiha Gökçen",
  AYT: "Antalya",
  DUB: "Dublin",
  EDI: "Édimbourg",
  CPH: "Copenhague",
  ARN: "Stockholm Arlanda",
  OSL: "Oslo",
  HEL: "Helsinki",
  KEF: "Reykjavik Keflavík",
  WAW: "Varsovie Chopin",
  PRG: "Prague",
  BUD: "Budapest",
  // Amérique du Nord
  JFK: "New York JFK",
  EWR: "New York Newark",
  LGA: "New York LaGuardia",
  LAX: "Los Angeles",
  SFO: "San Francisco",
  MIA: "Miami",
  MCO: "Orlando",
  ORD: "Chicago O'Hare",
  ATL: "Atlanta",
  BOS: "Boston Logan",
  IAD: "Washington Dulles",
  DCA: "Washington Reagan",
  SEA: "Seattle Tacoma",
  LAS: "Las Vegas",
  DFW: "Dallas Fort Worth",
  IAH: "Houston",
  PHX: "Phoenix",
  DEN: "Denver",
  YUL: "Montréal Trudeau",
  YYZ: "Toronto Pearson",
  YVR: "Vancouver",
  MEX: "Mexico",
  CUN: "Cancún",
  // Caraïbes & Amérique latine
  PTP: "Pointe-à-Pitre",
  FDF: "Fort-de-France",
  SXM: "Saint-Martin",
  HAV: "La Havane",
  PUJ: "Punta Cana",
  SDQ: "Saint-Domingue",
  NAS: "Nassau (Bahamas)",
  GIG: "Rio de Janeiro Galeão",
  GRU: "São Paulo Guarulhos",
  EZE: "Buenos Aires Ezeiza",
  SCL: "Santiago du Chili",
  LIM: "Lima",
  BOG: "Bogota",
  // Asie & Océanie
  DXB: "Dubaï",
  AUH: "Abou Dhabi",
  DOH: "Doha",
  RUH: "Riyad",
  JED: "Djeddah",
  TLV: "Tel Aviv Ben Gourion",
  BKK: "Bangkok Suvarnabhumi",
  DMK: "Bangkok Don Mueang",
  HKT: "Phuket",
  USM: "Koh Samui",
  KBV: "Krabi",
  SIN: "Singapour Changi",
  KUL: "Kuala Lumpur",
  HKG: "Hong Kong",
  PEK: "Pékin Capital",
  PKX: "Pékin Daxing",
  PVG: "Shanghai Pudong",
  CAN: "Canton (Guangzhou)",
  NRT: "Tokyo Narita",
  HND: "Tokyo Haneda",
  KIX: "Osaka Kansai",
  ICN: "Séoul Incheon",
  TPE: "Taipei Taoyuan",
  MNL: "Manille",
  CGK: "Jakarta",
  DPS: "Bali Denpasar",
  DEL: "Delhi",
  BOM: "Mumbai",
  MAA: "Chennai",
  BLR: "Bangalore",
  CMB: "Colombo",
  MLE: "Malé (Maldives)",
  KTM: "Katmandou",
  SYD: "Sydney",
  MEL: "Melbourne",
  AKL: "Auckland",
  NOU: "Nouméa",
  PPT: "Tahiti Papeete",
  // Afrique & Océan Indien
  CAI: "Le Caire",
  HRG: "Hurghada",
  SSH: "Charm el-Cheikh",
  CMN: "Casablanca Mohammed V",
  RAK: "Marrakech Ménara",
  AGA: "Agadir",
  TUN: "Tunis Carthage",
  DJE: "Djerba",
  ALG: "Alger Houari Boumédiène",
  DKR: "Dakar",
  ABJ: "Abidjan",
  COO: "Cotonou",
  LFW: "Lomé",
  DLA: "Douala",
  NSI: "Yaoundé",
  ADD: "Addis-Abeba",
  NBO: "Nairobi",
  ZNZ: "Zanzibar",
  JNB: "Johannesburg",
  CPT: "Le Cap",
  MRU: "Maurice",
  RUN: "La Réunion Roland Garros",
  TNR: "Antananarivo",
  SEZ: "Mahé (Seychelles)",
};

/** Renvoie le nom lisible d'un code IATA, ou le code lui-même si inconnu. */
export function iataToCity(code: string): string {
  const c = code.trim().toUpperCase();
  return IATA_AIRPORTS[c] ?? c;
}

/**
 * Formate un routing brut saisi côté admin pour un affichage client.
 * - "MRS → CDG → JFK" devient "Marseille Provence → Paris Charles-de-Gaulle → New York JFK"
 * - Préserve les séparateurs, sauts de ligne, et tronçons multi-mots.
 * - Détecte les codes IATA (3 lettres majuscules isolés).
 */
export function formatRoutingForClient(routing: string | null | undefined): string {
  if (!routing) return "";
  // Remplace tout token isolé de 3 lettres majuscules par son nom lisible.
  // \b évite de toucher aux mots plus longs ; on garde les chiffres/numéros de vol intacts.
  return routing.replace(/\b([A-Z]{3})\b/g, (m) => IATA_AIRPORTS[m] ?? m);
}
