// Dictionnaire des principaux codes IATA → nom de VILLE lisible pour le client.
// Règle : on affiche la ville que le client connaît et dont il rêve, pas le nom technique de l'aéroport.
// Quand une ville a plusieurs aéroports, on garde le nom de la ville seule (le client ne distingue pas).
// Exception : îles ou destinations où le nom de l'île EST la destination (Bali, Zanzibar, Mykonos…).

export const IATA_AIRPORTS: Record<string, string> = {
  // France
  CDG: "Paris",
  ORY: "Paris",
  LBG: "Paris",
  BVA: "Paris",
  MRS: "Marseille",
  NCE: "Nice",
  LYS: "Lyon",
  TLS: "Toulouse",
  BOD: "Bordeaux",
  NTE: "Nantes",
  MPL: "Montpellier",
  SXB: "Strasbourg",
  BIQ: "Biarritz",
  AJA: "Ajaccio",
  BIA: "Bastia",
  FSC: "Figari",
  CLY: "Calvi",
  RNS: "Rennes",
  BES: "Brest",
  LIL: "Lille",
  // Europe
  LHR: "Londres",
  LGW: "Londres",
  STN: "Londres",
  LCY: "Londres",
  LTN: "Londres",
  AMS: "Amsterdam",
  BRU: "Bruxelles",
  CRL: "Bruxelles",
  FRA: "Francfort",
  MUC: "Munich",
  TXL: "Berlin",
  BER: "Berlin",
  HAM: "Hambourg",
  DUS: "Düsseldorf",
  CGN: "Cologne",
  ZRH: "Zurich",
  GVA: "Genève",
  BSL: "Bâle",
  VIE: "Vienne",
  MAD: "Madrid",
  BCN: "Barcelone",
  AGP: "Malaga",
  PMI: "Palma de Majorque",
  IBZ: "Ibiza",
  ALC: "Alicante",
  SVQ: "Séville",
  VLC: "Valence",
  LIS: "Lisbonne",
  OPO: "Porto",
  FAO: "Faro",
  FNC: "Madère",
  FUE: "Fuerteventura",
  LPA: "Gran Canaria",
  TFS: "Ténérife",
  ACE: "Lanzarote",
  FCO: "Rome",
  CIA: "Rome",
  MXP: "Milan",
  LIN: "Milan",
  BGY: "Milan",
  VCE: "Venise",
  NAP: "Naples",
  CTA: "Catane",
  PMO: "Palerme",
  OLB: "Sardaigne",
  CAG: "Cagliari",
  ATH: "Athènes",
  JTR: "Santorin",
  JMK: "Mykonos",
  HER: "Héraklion",
  RHO: "Rhodes",
  SKG: "Thessalonique",
  CFU: "Corfou",
  KGS: "Kos",
  CHQ: "La Canée",
  ZTH: "Zakynthos",
  MJT: "Lesbos",
  PVK: "Préveza",
  IST: "Istanbul",
  SAW: "Istanbul",
  ADB: "Izmir",
  AYT: "Antalya",
  DLM: "Dalaman",
  BJV: "Bodrum",
  DUB: "Dublin",
  EDI: "Édimbourg",
  CPH: "Copenhague",
  ARN: "Stockholm",
  OSL: "Oslo",
  HEL: "Helsinki",
  KEF: "Reykjavik",
  WAW: "Varsovie",
  PRG: "Prague",
  BUD: "Budapest",
  OTP: "Bucarest",
  SOF: "Sofia",
  // Ville-codes groupés (alias métro)
  NYC: "New York",
  LON: "Londres",
  PAR: "Paris",
  MIL: "Milan",
  ROM: "Rome",
  TYO: "Tokyo",
  WAS: "Washington",
  // Moyen-Orient
  DXB: "Dubaï",
  AUH: "Abu Dhabi",
  SHJ: "Sharjah",
  DOH: "Doha",
  KWI: "Koweït",
  BAH: "Bahreïn",
  MCT: "Mascate",
  RUH: "Riyad",
  JED: "Djeddah",
  TLV: "Tel Aviv",
  AMM: "Amman",
  BEY: "Beyrouth",
  // Asie du Sud-Est
  BKK: "Bangkok",
  DMK: "Bangkok",
  HKT: "Phuket",
  CNX: "Chiang Mai",
  USM: "Koh Samui",
  KBV: "Krabi",
  NST: "Nakhon Si Thammarat",
  SIN: "Singapour",
  KUL: "Kuala Lumpur",
  LGK: "Langkawi",
  PEN: "Penang",
  BKI: "Kota Kinabalu",
  HAN: "Hanoï",
  SGN: "Hô Chi Minh-Ville",
  DAD: "Da Nang",
  PQC: "Phú Quốc",
  CXR: "Nha Trang",
  HPH: "Haïphong",
  REP: "Siem Reap",
  PNH: "Phnom Penh",
  LPQ: "Luang Prabang",
  VTE: "Vientiane",
  RGN: "Rangoun",
  MDL: "Mandalay",
  NYT: "Naypyidaw",
  // Indonésie — noms de villes/îles connus des clients
  CGK: "Jakarta",
  HLP: "Jakarta",
  DPS: "Bali",
  YIA: "Yogyakarta",
  JOG: "Yogyakarta",
  SUB: "Surabaya",
  SRG: "Semarang",
  LOP: "Lombok",
  UPG: "Makassar",
  BPN: "Balikpapan",
  MDC: "Manado",
  KOE: "Kupang",
  BTH: "Batam",
  PDG: "Padang",
  PKU: "Pekanbaru",
  PLM: "Palembang",
  LBJ: "Labuan Bajo",
  MOF: "Maumere",
  TMC: "Tambolaka",
  BMU: "Bima",
  AMQ: "Ambon",
  DJJ: "Jayapura",
  // Asie du Sud
  DEL: "Delhi",
  BOM: "Mumbai",
  MAA: "Chennai",
  BLR: "Bangalore",
  CCU: "Calcutta",
  HYD: "Hyderabad",
  GOI: "Goa",
  COK: "Kochi",
  TRV: "Trivandrum",
  IXB: "Bagdogra",
  GAU: "Guwahati",
  CMB: "Colombo",
  MLE: "Malé",
  KTM: "Katmandou",
  DAC: "Dacca",
  // Asie du Nord-Est
  PVG: "Shanghai",
  PEK: "Pékin",
  CAN: "Canton",
  CTU: "Chengdu",
  XIY: "Xi'an",
  SHA: "Shanghai",
  SZX: "Shenzhen",
  NRT: "Tokyo",
  HND: "Tokyo",
  KIX: "Osaka",
  FUK: "Fukuoka",
  CTS: "Sapporo",
  OKA: "Okinawa",
  NGO: "Nagoya",
  ICN: "Séoul",
  GMP: "Séoul",
  PUS: "Busan",
  CJU: "Jeju",
  TPE: "Taipei",
  KHH: "Kaohsiung",
  RMQ: "Taichung",
  HKG: "Hong Kong",
  MNL: "Manille",
  CEB: "Cebu",
  ILO: "Iloilo",
  PPS: "Puerto Princesa",
  DVO: "Davao",
  KLO: "Kalibo",
  // Océanie
  SYD: "Sydney",
  MEL: "Melbourne",
  BNE: "Brisbane",
  PER: "Perth",
  ADL: "Adélaïde",
  OOL: "Gold Coast",
  CNS: "Cairns",
  HBA: "Hobart",
  AKL: "Auckland",
  CHC: "Christchurch",
  WLG: "Wellington",
  ZQN: "Queenstown",
  NAN: "Fidji",
  PPT: "Tahiti",
  NOU: "Nouméa",
  // Afrique du Nord
  CAI: "Le Caire",
  HRG: "Hurghada",
  SSH: "Charm el-Cheikh",
  LXR: "Louxor",
  CMN: "Casablanca",
  RAK: "Marrakech",
  AGA: "Agadir",
  TNG: "Tanger",
  FEZ: "Fès",
  TUN: "Tunis",
  DJE: "Djerba",
  SFA: "Sfax",
  MIR: "Monastir",
  ALG: "Alger",
  ORN: "Oran",
  // Afrique subsaharienne
  DKR: "Dakar",
  ABJ: "Abidjan",
  ACC: "Accra",
  COO: "Cotonou",
  LFW: "Lomé",
  ABV: "Abuja",
  LOS: "Lagos",
  DLA: "Douala",
  NSI: "Yaoundé",
  ADD: "Addis-Abeba",
  NBO: "Nairobi",
  MBA: "Mombasa",
  ZNZ: "Zanzibar",
  DAR: "Dar es Salaam",
  KGL: "Kigali",
  EBB: "Kampala",
  KRT: "Khartoum",
  JUB: "Juba",
  LAD: "Luanda",
  MPM: "Maputo",
  HRE: "Harare",
  LUN: "Lusaka",
  WDH: "Windhoek",
  GBE: "Gaborone",
  JNB: "Johannesburg",
  DUR: "Durban",
  CPT: "Le Cap",
  MRU: "Maurice",
  RUN: "La Réunion",
  TNR: "Antananarivo",
  SEZ: "Mahé",
  // Amériques
  JFK: "New York",
  LGA: "New York",
  EWR: "New York",
  LAX: "Los Angeles",
  SFO: "San Francisco",
  ORD: "Chicago",
  MIA: "Miami",
  ATL: "Atlanta",
  DFW: "Dallas",
  BOS: "Boston",
  SEA: "Seattle",
  DEN: "Denver",
  LAS: "Las Vegas",
  MCO: "Orlando",
  PHX: "Phoenix",
  YUL: "Montréal",
  YYZ: "Toronto",
  YVR: "Vancouver",
  YYC: "Calgary",
  YOW: "Ottawa",
  GRU: "São Paulo",
  GIG: "Rio de Janeiro",
  BSB: "Brasilia",
  SSA: "Salvador",
  FOR: "Fortaleza",
  REC: "Recife",
  CWB: "Curitiba",
  EZE: "Buenos Aires",
  AEP: "Buenos Aires",
  COR: "Córdoba",
  SCL: "Santiago",
  LIM: "Lima",
  BOG: "Bogotá",
  UIO: "Quito",
  GYE: "Guayaquil",
  CCS: "Caracas",
  MEX: "Mexico",
  CUN: "Cancún",
  GDL: "Guadalajara",
  MTY: "Monterrey",
  HAV: "La Havane",
  SJO: "San José",
  PTY: "Panama",
};

/** Renvoie le nom de ville lisible pour un code IATA.
 *  Retourne le code brut si inconnu (ex: "XYZ").
 *  Les noms dans IATA_AIRPORTS sont déjà des noms de villes clients
 *  (pas de suffixe technique type "International" ou "Soekarno-Hatta").
 */
export function iataToCity(code: string): string {
  const c = code.trim().toUpperCase();
  return IATA_AIRPORTS[c] ?? c;
}

/** Table IATA → code pays ISO-2. Couvre les aéroports présents dans IATA_AIRPORTS
 *  + les destinations les plus courantes pour les agences de voyage françaises.
 *  Utilisée pour détecter les vols domestiques sans recourir au préfixe IATA (non fiable).
 */
export const IATA_COUNTRY: Record<string, string> = {
  // France
  CDG: "FR",
  ORY: "FR",
  LBG: "FR",
  BVA: "FR",
  MRS: "FR",
  NCE: "FR",
  LYS: "FR",
  TLS: "FR",
  BOD: "FR",
  NTE: "FR",
  MPL: "FR",
  SXB: "FR",
  BIQ: "FR",
  AJA: "FR",
  BIA: "FR",
  FSC: "FR",
  CLY: "FR",
  RNS: "FR",
  BES: "FR",
  LIL: "FR",
  // Europe
  LHR: "GB",
  LGW: "GB",
  STN: "GB",
  LCY: "GB",
  LTN: "GB",
  AMS: "NL",
  BRU: "BE",
  CRL: "BE",
  FRA: "DE",
  MUC: "DE",
  TXL: "DE",
  BER: "DE",
  HAM: "DE",
  DUS: "DE",
  CGN: "DE",
  ZRH: "CH",
  GVA: "CH",
  BSL: "CH",
  VIE: "AT",
  MAD: "ES",
  BCN: "ES",
  AGP: "ES",
  PMI: "ES",
  IBZ: "ES",
  ALC: "ES",
  SVQ: "ES",
  VLC: "ES",
  FCO: "IT",
  MXP: "IT",
  LIN: "IT",
  NAP: "IT",
  PMO: "IT",
  CTA: "IT",
  OLB: "IT",
  CAG: "IT",
  LIS: "PT",
  OPO: "PT",
  FAO: "PT",
  FUE: "ES",
  LPA: "ES",
  TFS: "ES",
  ACE: "ES",
  ATH: "GR",
  HER: "GR",
  RHO: "GR",
  SKG: "GR",
  CFU: "GR",
  JTR: "GR",
  KGS: "GR",
  CHQ: "GR",
  ZTH: "GR",
  MJT: "GR",
  PVK: "GR",
  CPH: "DK",
  ARN: "SE",
  OSL: "NO",
  HEL: "FI",
  DUB: "IE",
  WAW: "PL",
  PRG: "CZ",
  BUD: "HU",
  OTP: "RO",
  SOF: "BG",
  IST: "TR",
  SAW: "TR",
  ADB: "TR",
  AYT: "TR",
  DLM: "TR",
  BJV: "TR",
  // Afrique
  CMN: "MA",
  RAK: "MA",
  AGA: "MA",
  TNG: "MA",
  FEZ: "MA",
  TUN: "TN",
  SFA: "TN",
  MIR: "TN",
  ALG: "DZ",
  ORN: "DZ",
  CAI: "EG",
  HRG: "EG",
  SSH: "EG",
  LXR: "EG",
  ABV: "NG",
  LOS: "NG",
  NBO: "KE",
  MBA: "KE",
  DAR: "TZ",
  ZNZ: "TZ",
  ADD: "ET",
  ACC: "GH",
  DKR: "SN",
  ABJ: "CI",
  CPT: "ZA",
  JNB: "ZA",
  DUR: "ZA",
  MRU: "MU",
  RUN: "RE",
  TNR: "MG",
  SEZ: "SC",
  // Moyen-Orient
  DXB: "AE",
  AUH: "AE",
  SHJ: "AE",
  DOH: "QA",
  KWI: "KW",
  BAH: "BH",
  MCT: "OM",
  RUH: "SA",
  JED: "SA",
  TLV: "IL",
  AMM: "JO",
  BEY: "LB",
  // Asie
  BKK: "TH",
  DMK: "TH",
  HKT: "TH",
  CNX: "TH",
  USM: "TH",
  KBV: "TH",
  NST: "TH",
  SIN: "SG",
  KUL: "MY",
  LGK: "MY",
  PEN: "MY",
  BKI: "MY",
  HAN: "VN",
  SGN: "VN",
  DAD: "VN",
  PQC: "VN",
  CXR: "VN",
  HPH: "VN",
  REP: "KH",
  PNH: "KH",
  LPQ: "LA",
  VTE: "LA",
  RGN: "MM",
  MDL: "MM",
  NYT: "MM",
  DEL: "IN",
  BOM: "IN",
  MAA: "IN",
  BLR: "IN",
  CCU: "IN",
  HYD: "IN",
  GOI: "IN",
  COK: "IN",
  TRV: "IN",
  IXB: "IN",
  GAU: "IN",
  CMB: "LK",
  MLE: "MV",
  KTM: "NP",
  DAC: "BD",
  PVG: "CN",
  PEK: "CN",
  CAN: "CN",
  CTU: "CN",
  XIY: "CN",
  SHA: "CN",
  SZX: "CN",
  NRT: "JP",
  HND: "JP",
  KIX: "JP",
  FUK: "JP",
  CTS: "JP",
  OKA: "JP",
  NGO: "JP",
  ICN: "KR",
  PUS: "KR",
  CJU: "KR",
  GMP: "KR",
  TPE: "TW",
  KHH: "TW",
  RMQ: "TW",
  MNL: "PH",
  CEB: "PH",
  ILO: "PH",
  PPS: "PH",
  DVO: "PH",
  KLO: "PH",
  // Indonésie — aucun code ne partage de préfixe commun
  CGK: "ID",
  HLP: "ID",
  DPS: "ID",
  YIA: "ID",
  JOG: "ID",
  SUB: "ID",
  SRG: "ID",
  LOP: "ID",
  UPG: "ID",
  BPN: "ID",
  MDC: "ID",
  KOE: "ID",
  BTH: "ID",
  PDG: "ID",
  PKU: "ID",
  PLM: "ID",
  LBJ: "ID",
  MOF: "ID",
  TMC: "ID",
  BMU: "ID",
  AMQ: "ID",
  DJJ: "ID",
  SRI: "ID",
  TTR: "ID",
  // Océanie
  SYD: "AU",
  MEL: "AU",
  BNE: "AU",
  PER: "AU",
  ADL: "AU",
  OOL: "AU",
  CNS: "AU",
  HBA: "AU",
  AKL: "NZ",
  CHC: "NZ",
  WLG: "NZ",
  ZQN: "NZ",
  NAN: "FJ",
  PPT: "PF",
  // Amériques
  JFK: "US",
  LGA: "US",
  EWR: "US",
  LAX: "US",
  SFO: "US",
  ORD: "US",
  MIA: "US",
  ATL: "US",
  DFW: "US",
  BOS: "US",
  SEA: "US",
  DEN: "US",
  LAS: "US",
  MCO: "US",
  PHX: "US",
  YUL: "CA",
  YYZ: "CA",
  YVR: "CA",
  YYC: "CA",
  YOW: "CA",
  GRU: "BR",
  GIG: "BR",
  BSB: "BR",
  SSA: "BR",
  FOR: "BR",
  REC: "BR",
  CWB: "BR",
  EZE: "AR",
  AEP: "AR",
  COR: "AR",
  SCL: "CL",
  LIM: "PE",
  BOG: "CO",
  UIO: "EC",
  GYE: "EC",
  CCS: "VE",
  MEX: "MX",
  CUN: "MX",
  GDL: "MX",
  MTY: "MX",
  HAV: "CU",
  SJO: "CR",
  PTY: "PA",
};

/**
 * Formate un routing brut saisi côté admin pour un affichage client.
 * - "MRS → CDG → JFK" devient "Marseille Provence → Paris Charles-de-Gaulle → New York JFK"
 * - Préserve les séparateurs, sauts de ligne, et tronçons multi-mots.
 * - Détecte les codes IATA (3 lettres majuscules isolés).
 */
export function formatRoutingForClient(routing: string | null | undefined): string {
  if (!routing) return "";
  // Traite chaque ligne séparément (préserve aller / retour saisis sur 2 lignes).
  return routing
    .split(/\r?\n/)
    .map((line) => {
      const trimmed = line.trim();
      if (!trimmed) return "";
      // Si la ligne ne contient QUE des codes IATA + séparateurs (espaces, virgules,
      // tirets, slashes, flèches), on la reconstruit proprement avec " → ".
      const codesOnly = /^[A-Z]{3}([\s,\-/>→•·|]+[A-Z]{3})*$/i.test(trimmed);
      if (codesOnly) {
        const codes = trimmed.match(/[A-Z]{3}/gi) ?? [];
        return codes.map((c) => iataToCity(c)).join(" → ");
      }
      // Sinon : remplace simplement les codes isolés par leur nom lisible.
      return trimmed.replace(/\b([A-Z]{3})\b/g, (m) => IATA_AIRPORTS[m.toUpperCase()] ?? m);
    })
    .join("\n");
}
