/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UtilisateursRouteImport } from './routes/utilisateurs'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ReinitialiserMotDePasseRouteImport } from './routes/reinitialiser-mot-de-passe'
import { Route as RapprochementRouteImport } from './routes/rapprochement'
import { Route as QaRouteImport } from './routes/qa'
import { Route as PrevisionsRouteImport } from './routes/previsions'
import { Route as PilotageRouteImport } from './routes/pilotage'
import { Route as ParametresAgenceRouteImport } from './routes/parametres-agence'
import { Route as PaiementsRouteImport } from './routes/paiements'
import { Route as MotDePasseOublieRouteImport } from './routes/mot-de-passe-oublie'
import { Route as InscriptionAgenceRouteImport } from './routes/inscription-agence'
import { Route as ImportPdfRouteImport } from './routes/import-pdf'
import { Route as ImportBancaireRouteImport } from './routes/import-bancaire'
import { Route as ExportRouteImport } from './routes/export'
import { Route as DossiersRouteImport } from './routes/dossiers'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DemandesRouteImport } from './routes/demandes'
import { Route as CouverturesFxRouteImport } from './routes/couvertures-fx'
import { Route as CotationsRouteImport } from './routes/cotations'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as ComptesRouteImport } from './routes/comptes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminMessagesRouteImport } from './routes/admin-messages'
import { Route as AdminErrorsRouteImport } from './routes/admin-errors'
import { Route as AdminDemosRouteImport } from './routes/admin-demos'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as AdminAgencesRouteImport } from './routes/admin-agences'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as FacturesIdRouteImport } from './routes/factures.$id'
import { Route as DossiersIdRouteImport } from './routes/dossiers.$id'
import { Route as DemandesIdRouteImport } from './routes/demandes.$id'
import { Route as CotationsIdRouteImport } from './routes/cotations.$id'
import { Route as ContactsIdRouteImport } from './routes/contacts.$id'
import { Route as DemoVTokenRouteImport } from './routes/demo.v.$token'
import { Route as DemoRdvTokenRouteImport } from './routes/demo.rdv.$token'

const UtilisateursRoute = UtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ReinitialiserMotDePasseRoute = ReinitialiserMotDePasseRouteImport.update({
  id: '/reinitialiser-mot-de-passe',
  path: '/reinitialiser-mot-de-passe',
  getParentRoute: () => rootRouteImport,
} as any)
const RapprochementRoute = RapprochementRouteImport.update({
  id: '/rapprochement',
  path: '/rapprochement',
  getParentRoute: () => rootRouteImport,
} as any)
const QaRoute = QaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const PrevisionsRoute = PrevisionsRouteImport.update({
  id: '/previsions',
  path: '/previsions',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotageRoute = PilotageRouteImport.update({
  id: '/pilotage',
  path: '/pilotage',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresAgenceRoute = ParametresAgenceRouteImport.update({
  id: '/parametres-agence',
  path: '/parametres-agence',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementsRoute = PaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => rootRouteImport,
} as any)
const MotDePasseOublieRoute = MotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionAgenceRoute = InscriptionAgenceRouteImport.update({
  id: '/inscription-agence',
  path: '/inscription-agence',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportPdfRoute = ImportPdfRouteImport.update({
  id: '/import-pdf',
  path: '/import-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportBancaireRoute = ImportBancaireRouteImport.update({
  id: '/import-bancaire',
  path: '/import-bancaire',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const DossiersRoute = DossiersRouteImport.update({
  id: '/dossiers',
  path: '/dossiers',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandesRoute = DemandesRouteImport.update({
  id: '/demandes',
  path: '/demandes',
  getParentRoute: () => rootRouteImport,
} as any)
const CouverturesFxRoute = CouverturesFxRouteImport.update({
  id: '/couvertures-fx',
  path: '/couvertures-fx',
  getParentRoute: () => rootRouteImport,
} as any)
const CotationsRoute = CotationsRouteImport.update({
  id: '/cotations',
  path: '/cotations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ComptesRoute = ComptesRouteImport.update({
  id: '/comptes',
  path: '/comptes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/admin-messages',
  path: '/admin-messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminErrorsRoute = AdminErrorsRouteImport.update({
  id: '/admin-errors',
  path: '/admin-errors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDemosRoute = AdminDemosRouteImport.update({
  id: '/admin-demos',
  path: '/admin-demos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgencesRoute = AdminAgencesRouteImport.update({
  id: '/admin-agences',
  path: '/admin-agences',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturesIdRoute = FacturesIdRouteImport.update({
  id: '/factures/$id',
  path: '/factures/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DossiersIdRoute = DossiersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DossiersRoute,
} as any)
const DemandesIdRoute = DemandesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DemandesRoute,
} as any)
const CotationsIdRoute = CotationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CotationsRoute,
} as any)
const ContactsIdRoute = ContactsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ContactsRoute,
} as any)
const DemoVTokenRoute = DemoVTokenRouteImport.update({
  id: '/v/$token',
  path: '/v/$token',
  getParentRoute: () => DemoRoute,
} as any)
const DemoRdvTokenRoute = DemoRdvTokenRouteImport.update({
  id: '/rdv/$token',
  path: '/rdv/$token',
  getParentRoute: () => DemoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-agences': typeof AdminAgencesRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-demos': typeof AdminDemosRoute
  '/admin-errors': typeof AdminErrorsRoute
  '/admin-messages': typeof AdminMessagesRoute
  '/app': typeof AppRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/comptes': typeof ComptesRoute
  '/contacts': typeof ContactsRouteWithChildren
  '/cotations': typeof CotationsRouteWithChildren
  '/couvertures-fx': typeof CouverturesFxRoute
  '/demandes': typeof DemandesRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/dossiers': typeof DossiersRouteWithChildren
  '/export': typeof ExportRoute
  '/import-bancaire': typeof ImportBancaireRoute
  '/import-pdf': typeof ImportPdfRoute
  '/inscription-agence': typeof InscriptionAgenceRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/paiements': typeof PaiementsRoute
  '/parametres-agence': typeof ParametresAgenceRoute
  '/pilotage': typeof PilotageRoute
  '/previsions': typeof PrevisionsRoute
  '/qa': typeof QaRoute
  '/rapprochement': typeof RapprochementRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/support': typeof SupportRoute
  '/tarifs': typeof TarifsRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/cotations/$id': typeof CotationsIdRoute
  '/demandes/$id': typeof DemandesIdRoute
  '/dossiers/$id': typeof DossiersIdRoute
  '/factures/$id': typeof FacturesIdRoute
  '/p/$token': typeof PTokenRoute
  '/demo/rdv/$token': typeof DemoRdvTokenRoute
  '/demo/v/$token': typeof DemoVTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-agences': typeof AdminAgencesRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-demos': typeof AdminDemosRoute
  '/admin-errors': typeof AdminErrorsRoute
  '/admin-messages': typeof AdminMessagesRoute
  '/app': typeof AppRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/comptes': typeof ComptesRoute
  '/contacts': typeof ContactsRouteWithChildren
  '/cotations': typeof CotationsRouteWithChildren
  '/couvertures-fx': typeof CouverturesFxRoute
  '/demandes': typeof DemandesRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/dossiers': typeof DossiersRouteWithChildren
  '/export': typeof ExportRoute
  '/import-bancaire': typeof ImportBancaireRoute
  '/import-pdf': typeof ImportPdfRoute
  '/inscription-agence': typeof InscriptionAgenceRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/paiements': typeof PaiementsRoute
  '/parametres-agence': typeof ParametresAgenceRoute
  '/pilotage': typeof PilotageRoute
  '/previsions': typeof PrevisionsRoute
  '/qa': typeof QaRoute
  '/rapprochement': typeof RapprochementRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/support': typeof SupportRoute
  '/tarifs': typeof TarifsRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/cotations/$id': typeof CotationsIdRoute
  '/demandes/$id': typeof DemandesIdRoute
  '/dossiers/$id': typeof DossiersIdRoute
  '/factures/$id': typeof FacturesIdRoute
  '/p/$token': typeof PTokenRoute
  '/demo/rdv/$token': typeof DemoRdvTokenRoute
  '/demo/v/$token': typeof DemoVTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-agences': typeof AdminAgencesRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-demos': typeof AdminDemosRoute
  '/admin-errors': typeof AdminErrorsRoute
  '/admin-messages': typeof AdminMessagesRoute
  '/app': typeof AppRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/comptes': typeof ComptesRoute
  '/contacts': typeof ContactsRouteWithChildren
  '/cotations': typeof CotationsRouteWithChildren
  '/couvertures-fx': typeof CouverturesFxRoute
  '/demandes': typeof DemandesRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/dossiers': typeof DossiersRouteWithChildren
  '/export': typeof ExportRoute
  '/import-bancaire': typeof ImportBancaireRoute
  '/import-pdf': typeof ImportPdfRoute
  '/inscription-agence': typeof InscriptionAgenceRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/paiements': typeof PaiementsRoute
  '/parametres-agence': typeof ParametresAgenceRoute
  '/pilotage': typeof PilotageRoute
  '/previsions': typeof PrevisionsRoute
  '/qa': typeof QaRoute
  '/rapprochement': typeof RapprochementRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/support': typeof SupportRoute
  '/tarifs': typeof TarifsRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/cotations/$id': typeof CotationsIdRoute
  '/demandes/$id': typeof DemandesIdRoute
  '/dossiers/$id': typeof DossiersIdRoute
  '/factures/$id': typeof FacturesIdRoute
  '/p/$token': typeof PTokenRoute
  '/demo/rdv/$token': typeof DemoRdvTokenRoute
  '/demo/v/$token': typeof DemoVTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-agences'
    | '/admin-dashboard'
    | '/admin-demos'
    | '/admin-errors'
    | '/admin-messages'
    | '/app'
    | '/audit'
    | '/auth'
    | '/comptes'
    | '/contacts'
    | '/cotations'
    | '/couvertures-fx'
    | '/demandes'
    | '/demo'
    | '/dossiers'
    | '/export'
    | '/import-bancaire'
    | '/import-pdf'
    | '/inscription-agence'
    | '/mot-de-passe-oublie'
    | '/paiements'
    | '/parametres-agence'
    | '/pilotage'
    | '/previsions'
    | '/qa'
    | '/rapprochement'
    | '/reinitialiser-mot-de-passe'
    | '/support'
    | '/tarifs'
    | '/utilisateurs'
    | '/contacts/$id'
    | '/cotations/$id'
    | '/demandes/$id'
    | '/dossiers/$id'
    | '/factures/$id'
    | '/p/$token'
    | '/demo/rdv/$token'
    | '/demo/v/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-agences'
    | '/admin-dashboard'
    | '/admin-demos'
    | '/admin-errors'
    | '/admin-messages'
    | '/app'
    | '/audit'
    | '/auth'
    | '/comptes'
    | '/contacts'
    | '/cotations'
    | '/couvertures-fx'
    | '/demandes'
    | '/demo'
    | '/dossiers'
    | '/export'
    | '/import-bancaire'
    | '/import-pdf'
    | '/inscription-agence'
    | '/mot-de-passe-oublie'
    | '/paiements'
    | '/parametres-agence'
    | '/pilotage'
    | '/previsions'
    | '/qa'
    | '/rapprochement'
    | '/reinitialiser-mot-de-passe'
    | '/support'
    | '/tarifs'
    | '/utilisateurs'
    | '/contacts/$id'
    | '/cotations/$id'
    | '/demandes/$id'
    | '/dossiers/$id'
    | '/factures/$id'
    | '/p/$token'
    | '/demo/rdv/$token'
    | '/demo/v/$token'
  id:
    | '__root__'
    | '/'
    | '/admin-agences'
    | '/admin-dashboard'
    | '/admin-demos'
    | '/admin-errors'
    | '/admin-messages'
    | '/app'
    | '/audit'
    | '/auth'
    | '/comptes'
    | '/contacts'
    | '/cotations'
    | '/couvertures-fx'
    | '/demandes'
    | '/demo'
    | '/dossiers'
    | '/export'
    | '/import-bancaire'
    | '/import-pdf'
    | '/inscription-agence'
    | '/mot-de-passe-oublie'
    | '/paiements'
    | '/parametres-agence'
    | '/pilotage'
    | '/previsions'
    | '/qa'
    | '/rapprochement'
    | '/reinitialiser-mot-de-passe'
    | '/support'
    | '/tarifs'
    | '/utilisateurs'
    | '/contacts/$id'
    | '/cotations/$id'
    | '/demandes/$id'
    | '/dossiers/$id'
    | '/factures/$id'
    | '/p/$token'
    | '/demo/rdv/$token'
    | '/demo/v/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAgencesRoute: typeof AdminAgencesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDemosRoute: typeof AdminDemosRoute
  AdminErrorsRoute: typeof AdminErrorsRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AppRoute: typeof AppRoute
  AuditRoute: typeof AuditRoute
  AuthRoute: typeof AuthRoute
  ComptesRoute: typeof ComptesRoute
  ContactsRoute: typeof ContactsRouteWithChildren
  CotationsRoute: typeof CotationsRouteWithChildren
  CouverturesFxRoute: typeof CouverturesFxRoute
  DemandesRoute: typeof DemandesRouteWithChildren
  DemoRoute: typeof DemoRouteWithChildren
  DossiersRoute: typeof DossiersRouteWithChildren
  ExportRoute: typeof ExportRoute
  ImportBancaireRoute: typeof ImportBancaireRoute
  ImportPdfRoute: typeof ImportPdfRoute
  InscriptionAgenceRoute: typeof InscriptionAgenceRoute
  MotDePasseOublieRoute: typeof MotDePasseOublieRoute
  PaiementsRoute: typeof PaiementsRoute
  ParametresAgenceRoute: typeof ParametresAgenceRoute
  PilotageRoute: typeof PilotageRoute
  PrevisionsRoute: typeof PrevisionsRoute
  QaRoute: typeof QaRoute
  RapprochementRoute: typeof RapprochementRoute
  ReinitialiserMotDePasseRoute: typeof ReinitialiserMotDePasseRoute
  SupportRoute: typeof SupportRoute
  TarifsRoute: typeof TarifsRoute
  UtilisateursRoute: typeof UtilisateursRoute
  FacturesIdRoute: typeof FacturesIdRoute
  PTokenRoute: typeof PTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/utilisateurs': {
      id: '/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/utilisateurs'
      preLoaderRoute: typeof UtilisateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reinitialiser-mot-de-passe': {
      id: '/reinitialiser-mot-de-passe'
      path: '/reinitialiser-mot-de-passe'
      fullPath: '/reinitialiser-mot-de-passe'
      preLoaderRoute: typeof ReinitialiserMotDePasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapprochement': {
      id: '/rapprochement'
      path: '/rapprochement'
      fullPath: '/rapprochement'
      preLoaderRoute: typeof RapprochementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa': {
      id: '/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof QaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/previsions': {
      id: '/previsions'
      path: '/previsions'
      fullPath: '/previsions'
      preLoaderRoute: typeof PrevisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilotage': {
      id: '/pilotage'
      path: '/pilotage'
      fullPath: '/pilotage'
      preLoaderRoute: typeof PilotageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres-agence': {
      id: '/parametres-agence'
      path: '/parametres-agence'
      fullPath: '/parametres-agence'
      preLoaderRoute: typeof ParametresAgenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiements': {
      id: '/paiements'
      path: '/paiements'
      fullPath: '/paiements'
      preLoaderRoute: typeof PaiementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mot-de-passe-oublie': {
      id: '/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof MotDePasseOublieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription-agence': {
      id: '/inscription-agence'
      path: '/inscription-agence'
      fullPath: '/inscription-agence'
      preLoaderRoute: typeof InscriptionAgenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-pdf': {
      id: '/import-pdf'
      path: '/import-pdf'
      fullPath: '/import-pdf'
      preLoaderRoute: typeof ImportPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-bancaire': {
      id: '/import-bancaire'
      path: '/import-bancaire'
      fullPath: '/import-bancaire'
      preLoaderRoute: typeof ImportBancaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossiers': {
      id: '/dossiers'
      path: '/dossiers'
      fullPath: '/dossiers'
      preLoaderRoute: typeof DossiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demandes': {
      id: '/demandes'
      path: '/demandes'
      fullPath: '/demandes'
      preLoaderRoute: typeof DemandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/couvertures-fx': {
      id: '/couvertures-fx'
      path: '/couvertures-fx'
      fullPath: '/couvertures-fx'
      preLoaderRoute: typeof CouverturesFxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotations': {
      id: '/cotations'
      path: '/cotations'
      fullPath: '/cotations'
      preLoaderRoute: typeof CotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comptes': {
      id: '/comptes'
      path: '/comptes'
      fullPath: '/comptes'
      preLoaderRoute: typeof ComptesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-messages': {
      id: '/admin-messages'
      path: '/admin-messages'
      fullPath: '/admin-messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-errors': {
      id: '/admin-errors'
      path: '/admin-errors'
      fullPath: '/admin-errors'
      preLoaderRoute: typeof AdminErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-demos': {
      id: '/admin-demos'
      path: '/admin-demos'
      fullPath: '/admin-demos'
      preLoaderRoute: typeof AdminDemosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-agences': {
      id: '/admin-agences'
      path: '/admin-agences'
      fullPath: '/admin-agences'
      preLoaderRoute: typeof AdminAgencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factures/$id': {
      id: '/factures/$id'
      path: '/factures/$id'
      fullPath: '/factures/$id'
      preLoaderRoute: typeof FacturesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossiers/$id': {
      id: '/dossiers/$id'
      path: '/$id'
      fullPath: '/dossiers/$id'
      preLoaderRoute: typeof DossiersIdRouteImport
      parentRoute: typeof DossiersRoute
    }
    '/demandes/$id': {
      id: '/demandes/$id'
      path: '/$id'
      fullPath: '/demandes/$id'
      preLoaderRoute: typeof DemandesIdRouteImport
      parentRoute: typeof DemandesRoute
    }
    '/cotations/$id': {
      id: '/cotations/$id'
      path: '/$id'
      fullPath: '/cotations/$id'
      preLoaderRoute: typeof CotationsIdRouteImport
      parentRoute: typeof CotationsRoute
    }
    '/contacts/$id': {
      id: '/contacts/$id'
      path: '/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof ContactsIdRouteImport
      parentRoute: typeof ContactsRoute
    }
    '/demo/v/$token': {
      id: '/demo/v/$token'
      path: '/v/$token'
      fullPath: '/demo/v/$token'
      preLoaderRoute: typeof DemoVTokenRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/rdv/$token': {
      id: '/demo/rdv/$token'
      path: '/rdv/$token'
      fullPath: '/demo/rdv/$token'
      preLoaderRoute: typeof DemoRdvTokenRouteImport
      parentRoute: typeof DemoRoute
    }
  }
}

interface ContactsRouteChildren {
  ContactsIdRoute: typeof ContactsIdRoute
}

const ContactsRouteChildren: ContactsRouteChildren = {
  ContactsIdRoute: ContactsIdRoute,
}

const ContactsRouteWithChildren = ContactsRoute._addFileChildren(
  ContactsRouteChildren,
)

interface CotationsRouteChildren {
  CotationsIdRoute: typeof CotationsIdRoute
}

const CotationsRouteChildren: CotationsRouteChildren = {
  CotationsIdRoute: CotationsIdRoute,
}

const CotationsRouteWithChildren = CotationsRoute._addFileChildren(
  CotationsRouteChildren,
)

interface DemandesRouteChildren {
  DemandesIdRoute: typeof DemandesIdRoute
}

const DemandesRouteChildren: DemandesRouteChildren = {
  DemandesIdRoute: DemandesIdRoute,
}

const DemandesRouteWithChildren = DemandesRoute._addFileChildren(
  DemandesRouteChildren,
)

interface DemoRouteChildren {
  DemoRdvTokenRoute: typeof DemoRdvTokenRoute
  DemoVTokenRoute: typeof DemoVTokenRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoRdvTokenRoute: DemoRdvTokenRoute,
  DemoVTokenRoute: DemoVTokenRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

interface DossiersRouteChildren {
  DossiersIdRoute: typeof DossiersIdRoute
}

const DossiersRouteChildren: DossiersRouteChildren = {
  DossiersIdRoute: DossiersIdRoute,
}

const DossiersRouteWithChildren = DossiersRoute._addFileChildren(
  DossiersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAgencesRoute: AdminAgencesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDemosRoute: AdminDemosRoute,
  AdminErrorsRoute: AdminErrorsRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AppRoute: AppRoute,
  AuditRoute: AuditRoute,
  AuthRoute: AuthRoute,
  ComptesRoute: ComptesRoute,
  ContactsRoute: ContactsRouteWithChildren,
  CotationsRoute: CotationsRouteWithChildren,
  CouverturesFxRoute: CouverturesFxRoute,
  DemandesRoute: DemandesRouteWithChildren,
  DemoRoute: DemoRouteWithChildren,
  DossiersRoute: DossiersRouteWithChildren,
  ExportRoute: ExportRoute,
  ImportBancaireRoute: ImportBancaireRoute,
  ImportPdfRoute: ImportPdfRoute,
  InscriptionAgenceRoute: InscriptionAgenceRoute,
  MotDePasseOublieRoute: MotDePasseOublieRoute,
  PaiementsRoute: PaiementsRoute,
  ParametresAgenceRoute: ParametresAgenceRoute,
  PilotageRoute: PilotageRoute,
  PrevisionsRoute: PrevisionsRoute,
  QaRoute: QaRoute,
  RapprochementRoute: RapprochementRoute,
  ReinitialiserMotDePasseRoute: ReinitialiserMotDePasseRoute,
  SupportRoute: SupportRoute,
  TarifsRoute: TarifsRoute,
  UtilisateursRoute: UtilisateursRoute,
  FacturesIdRoute: FacturesIdRoute,
  PTokenRoute: PTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
