/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UtilisateursRouteImport } from './routes/utilisateurs'
import { Route as RapprochementRouteImport } from './routes/rapprochement'
import { Route as PrevisionsRouteImport } from './routes/previsions'
import { Route as PilotageRouteImport } from './routes/pilotage'
import { Route as PaiementsRouteImport } from './routes/paiements'
import { Route as ImportBancaireRouteImport } from './routes/import-bancaire'
import { Route as ExportRouteImport } from './routes/export'
import { Route as DossiersRouteImport } from './routes/dossiers'
import { Route as CouverturesFxRouteImport } from './routes/couvertures-fx'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as ComptesRouteImport } from './routes/comptes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FacturesIdRouteImport } from './routes/factures.$id'
import { Route as DossiersIdRouteImport } from './routes/dossiers.$id'
import { Route as ContactsIdRouteImport } from './routes/contacts.$id'

const UtilisateursRoute = UtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const RapprochementRoute = RapprochementRouteImport.update({
  id: '/rapprochement',
  path: '/rapprochement',
  getParentRoute: () => rootRouteImport,
} as any)
const PrevisionsRoute = PrevisionsRouteImport.update({
  id: '/previsions',
  path: '/previsions',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotageRoute = PilotageRouteImport.update({
  id: '/pilotage',
  path: '/pilotage',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementsRoute = PaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportBancaireRoute = ImportBancaireRouteImport.update({
  id: '/import-bancaire',
  path: '/import-bancaire',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const DossiersRoute = DossiersRouteImport.update({
  id: '/dossiers',
  path: '/dossiers',
  getParentRoute: () => rootRouteImport,
} as any)
const CouverturesFxRoute = CouverturesFxRouteImport.update({
  id: '/couvertures-fx',
  path: '/couvertures-fx',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ComptesRoute = ComptesRouteImport.update({
  id: '/comptes',
  path: '/comptes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturesIdRoute = FacturesIdRouteImport.update({
  id: '/factures/$id',
  path: '/factures/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DossiersIdRoute = DossiersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DossiersRoute,
} as any)
const ContactsIdRoute = ContactsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ContactsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/comptes': typeof ComptesRoute
  '/contacts': typeof ContactsRouteWithChildren
  '/couvertures-fx': typeof CouverturesFxRoute
  '/dossiers': typeof DossiersRouteWithChildren
  '/export': typeof ExportRoute
  '/import-bancaire': typeof ImportBancaireRoute
  '/paiements': typeof PaiementsRoute
  '/pilotage': typeof PilotageRoute
  '/previsions': typeof PrevisionsRoute
  '/rapprochement': typeof RapprochementRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/dossiers/$id': typeof DossiersIdRoute
  '/factures/$id': typeof FacturesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/comptes': typeof ComptesRoute
  '/contacts': typeof ContactsRouteWithChildren
  '/couvertures-fx': typeof CouverturesFxRoute
  '/dossiers': typeof DossiersRouteWithChildren
  '/export': typeof ExportRoute
  '/import-bancaire': typeof ImportBancaireRoute
  '/paiements': typeof PaiementsRoute
  '/pilotage': typeof PilotageRoute
  '/previsions': typeof PrevisionsRoute
  '/rapprochement': typeof RapprochementRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/dossiers/$id': typeof DossiersIdRoute
  '/factures/$id': typeof FacturesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/comptes': typeof ComptesRoute
  '/contacts': typeof ContactsRouteWithChildren
  '/couvertures-fx': typeof CouverturesFxRoute
  '/dossiers': typeof DossiersRouteWithChildren
  '/export': typeof ExportRoute
  '/import-bancaire': typeof ImportBancaireRoute
  '/paiements': typeof PaiementsRoute
  '/pilotage': typeof PilotageRoute
  '/previsions': typeof PrevisionsRoute
  '/rapprochement': typeof RapprochementRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/dossiers/$id': typeof DossiersIdRoute
  '/factures/$id': typeof FacturesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/auth'
    | '/comptes'
    | '/contacts'
    | '/couvertures-fx'
    | '/dossiers'
    | '/export'
    | '/import-bancaire'
    | '/paiements'
    | '/pilotage'
    | '/previsions'
    | '/rapprochement'
    | '/utilisateurs'
    | '/contacts/$id'
    | '/dossiers/$id'
    | '/factures/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/auth'
    | '/comptes'
    | '/contacts'
    | '/couvertures-fx'
    | '/dossiers'
    | '/export'
    | '/import-bancaire'
    | '/paiements'
    | '/pilotage'
    | '/previsions'
    | '/rapprochement'
    | '/utilisateurs'
    | '/contacts/$id'
    | '/dossiers/$id'
    | '/factures/$id'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/auth'
    | '/comptes'
    | '/contacts'
    | '/couvertures-fx'
    | '/dossiers'
    | '/export'
    | '/import-bancaire'
    | '/paiements'
    | '/pilotage'
    | '/previsions'
    | '/rapprochement'
    | '/utilisateurs'
    | '/contacts/$id'
    | '/dossiers/$id'
    | '/factures/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  AuthRoute: typeof AuthRoute
  ComptesRoute: typeof ComptesRoute
  ContactsRoute: typeof ContactsRouteWithChildren
  CouverturesFxRoute: typeof CouverturesFxRoute
  DossiersRoute: typeof DossiersRouteWithChildren
  ExportRoute: typeof ExportRoute
  ImportBancaireRoute: typeof ImportBancaireRoute
  PaiementsRoute: typeof PaiementsRoute
  PilotageRoute: typeof PilotageRoute
  PrevisionsRoute: typeof PrevisionsRoute
  RapprochementRoute: typeof RapprochementRoute
  UtilisateursRoute: typeof UtilisateursRoute
  FacturesIdRoute: typeof FacturesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/utilisateurs': {
      id: '/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/utilisateurs'
      preLoaderRoute: typeof UtilisateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapprochement': {
      id: '/rapprochement'
      path: '/rapprochement'
      fullPath: '/rapprochement'
      preLoaderRoute: typeof RapprochementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/previsions': {
      id: '/previsions'
      path: '/previsions'
      fullPath: '/previsions'
      preLoaderRoute: typeof PrevisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilotage': {
      id: '/pilotage'
      path: '/pilotage'
      fullPath: '/pilotage'
      preLoaderRoute: typeof PilotageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiements': {
      id: '/paiements'
      path: '/paiements'
      fullPath: '/paiements'
      preLoaderRoute: typeof PaiementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-bancaire': {
      id: '/import-bancaire'
      path: '/import-bancaire'
      fullPath: '/import-bancaire'
      preLoaderRoute: typeof ImportBancaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossiers': {
      id: '/dossiers'
      path: '/dossiers'
      fullPath: '/dossiers'
      preLoaderRoute: typeof DossiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/couvertures-fx': {
      id: '/couvertures-fx'
      path: '/couvertures-fx'
      fullPath: '/couvertures-fx'
      preLoaderRoute: typeof CouverturesFxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comptes': {
      id: '/comptes'
      path: '/comptes'
      fullPath: '/comptes'
      preLoaderRoute: typeof ComptesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factures/$id': {
      id: '/factures/$id'
      path: '/factures/$id'
      fullPath: '/factures/$id'
      preLoaderRoute: typeof FacturesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossiers/$id': {
      id: '/dossiers/$id'
      path: '/$id'
      fullPath: '/dossiers/$id'
      preLoaderRoute: typeof DossiersIdRouteImport
      parentRoute: typeof DossiersRoute
    }
    '/contacts/$id': {
      id: '/contacts/$id'
      path: '/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof ContactsIdRouteImport
      parentRoute: typeof ContactsRoute
    }
  }
}

interface ContactsRouteChildren {
  ContactsIdRoute: typeof ContactsIdRoute
}

const ContactsRouteChildren: ContactsRouteChildren = {
  ContactsIdRoute: ContactsIdRoute,
}

const ContactsRouteWithChildren = ContactsRoute._addFileChildren(
  ContactsRouteChildren,
)

interface DossiersRouteChildren {
  DossiersIdRoute: typeof DossiersIdRoute
}

const DossiersRouteChildren: DossiersRouteChildren = {
  DossiersIdRoute: DossiersIdRoute,
}

const DossiersRouteWithChildren = DossiersRoute._addFileChildren(
  DossiersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  AuthRoute: AuthRoute,
  ComptesRoute: ComptesRoute,
  ContactsRoute: ContactsRouteWithChildren,
  CouverturesFxRoute: CouverturesFxRoute,
  DossiersRoute: DossiersRouteWithChildren,
  ExportRoute: ExportRoute,
  ImportBancaireRoute: ImportBancaireRoute,
  PaiementsRoute: PaiementsRoute,
  PilotageRoute: PilotageRoute,
  PrevisionsRoute: PrevisionsRoute,
  RapprochementRoute: RapprochementRoute,
  UtilisateursRoute: UtilisateursRoute,
  FacturesIdRoute: FacturesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
